### ISSUE TITLE
little responsive issue

### ISSUE THREAD

**Issue by Murat-Karakaya** [Frnt-End/Update-React-in-GitHub-Pages#3]
I actually love this repo. And it helped me a lot. But the sentence "git commit -m 'update build for gh-pages'" get's out of it's parent div block.

**Comment by Murat-Karakaya** [comment]
When I made the width of the tab of this website small enaugh, the portfolio button also got out of it's parent div block.

**Comment by Frnt-End** [comment]
I'm working on it:)

**Comment by Murat-Karakaya** [comment]
> I'm working on it:)

keep up the good work ;)

**Comment by Frnt-End** [comment]
Thank you for your feedback and for flagging this issue, now its fixed. the problem was due to the **default behavior** of **pre** tag code blocks extending beyond their containing **div**. more details about this problem and the solution can be found here: https://jocha.se/blog/tech/fix-pre-code-going-outside-div
